=== GunioRobot/eglooframework/trunk/XML/schemas/DBQueries.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="com.egloo.db.queries" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:DBQueries="com.egloo.db.queries">


	<xs:element name="Queries" type="DBQueries:Queries"></xs:element>

	<xs:complexType name="Queries">
		<xs:sequence>
			<xs:element name="PLSelect" type="DBQueries:PLSelect" maxOccurs="unbounded" minOccurs="0"></xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="PLSelect">
		<xs:sequence>
			<xs:element name="PLInputVariable" type="DBQueries:PLInputVariable" maxOccurs="unbounded" minOccurs="0"></xs:element>
			<xs:element name="PLOutputVariable" type="DBQueries:PLOutputVariable" maxOccurs="unbounded" minOccurs="0"></xs:element>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required"></xs:attribute>
		<xs:attribute name="multipleResults" type="xs:boolean" use="required"></xs:attribute>
		<xs:attribute name="functionName" type="xs:string" use="required"></xs:attribute>
	</xs:complexType>

	<xs:complexType name="PLInputVariable">
    	<xs:attribute name="name" type="xs:string" use="required"></xs:attribute>
    	<xs:attribute name="order" type="xs:int" use="required"></xs:attribute>
    </xs:complexType>

    <xs:complexType name="PLOutputVariable">
    	<xs:attribute name="name" type="xs:string" use="required"></xs:attribute>
    	<xs:attribute name="type" type="xs:string" use="required"></xs:attribute>
    </xs:complexType>
</xs:schema>

=== GunioRobot/eglooframework/trunk/XML/DBQueries.xml
<?xml version="1.0" encoding="UTF-8"?>
<DBQueries:Queries xmlns:DBQueries="com.egloo.db.queries"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="com.egloo.db.queries schemas/DBQueries.xsd ">
	<PLSelect name="rankElement" functionName="rankelement"
		multipleResults="false">
		<PLInputVariable order="0" name="profileID" />
		<PLInputVariable order="1" name="elementID" />
		<PLInputVariable order="2" name="rank" />
		<PLOutputVariable name="output_successful" type="boolean" />
		<PLOutputVariable name="output_dateranked" type="string" />
		<!--This function ranks an element-->
	</PLSelect>
	<PLSelect name="getProfileElementRanking"
		functionName="getprofileelementranking" multipleResults="false">
		<PLInputVariable order="0" name="elementID" />
		<PLInputVariable order="1" name="profileID" />
		<PLOutputVariable name="output_rank" type="string" />
		<PLOutputVariable name="output_dateranked" type="string" />
		<PLOutputVariable name="output_successful" type="boolean" />
	</PLSelect>
	<PLSelect name="getElementRanking" functionName="getelementranking"
		multipleResults="false">
		<PLInputVariable order="0" name="elementID" />
		<PLOutputVariable name="output_rank" type="string" />
		<PLOutputVariable name="output_successful" type="boolean" />
	</PLSelect>
	<PLSelect name="getElementInstance"
		functionName="getelementinstance" multipleResults="false">
		<PLInputVariable order="0" name="elementID" />
		<PLInputVariable order="1" name="profileID" />
		<PLOutputVariable name="output_elementtype_id" type="string" />
		<PLOutputVariable name="output_creator_id" type="string" />
		<PLOutputVariable name="output_elementpackagepath" type="string" />
		<PLOutputVariable name="output_datecreated" type="string" />
		<PLOutputVariable name="output_rankable" type="boolean" />
		<PLOutputVariable name="output_elementrank" type="string" />
		<PLOutputVariable name="output_profileelementrank" type="string" />
		<PLOutputVariable name="output_dateprofileranked" type="string" />
	</PLSelect>
	<PLSelect name="getCubeSingletonID"
		functionName="getcubesingletonid" multipleResults="false">
		<PLInputVariable order="0" name="elementTypeID" />
		<PLInputVariable order="1" name="creatorID" />
		<PLOutputVariable name="output_element_id" type="string" />
	</PLSelect>
	<PLSelect name="createNewCubeInstance"
		functionName="createnewcubeinstance" multipleResults="false">
		<PLInputVariable order="0" name="elementtypeID" />
		<PLInputVariable order="1" name="creatorID" />
		<PLOutputVariable name="output_element_id" type="string" />
		<PLOutputVariable name="output_successful" type="boolean" />
		<PLOutputVariable name="output_elementpackagepath" type="string" />
		<PLOutputVariable name="output_datecreated" type="string" />
		<PLOutputVariable name="output_rankable" type="boolean" />
		<PLOutputVariable name="output_elementrank" type="string" />
		<PLOutputVariable name="output_profileelementrank" type="string" />
		<PLOutputVariable name="output_dateprofileranked" type="string" />
		<PLOutputVariable name="output_rankable" type="boolean" />		
	</PLSelect>
	<PLSelect name="requestRelationship"
		functionName="requestRelationship" multipleResults="false">
		<PLInputVariable order="0" name="accepterProfileID" />
		<PLInputVariable order="1" name="requesterProfileID" />
		<PLInputVariable order="2" name="relationshipType" />
		<PLOutputVariable name="output_successful" type="boolean" />
	</PLSelect>
	<PLSelect name="actOnRelationship" functionName="actOnRelationship"
		multipleResults="false">
		<PLInputVariable order="0" name="requesterProfileID" />
		<PLInputVariable order="1" name="accepterProfileID" />
		<PLInputVariable order="2" name="relationshipType" />
		<PLInputVariable order="3" name="acceptRelationship" />
		<PLOutputVariable name="output_Successful" type="boolean" />
	</PLSelect>
	<PLSelect name="getProfileRelationshipRequests"
		functionName="getProfileRelationshipRequests" multipleResults="true">
		<PLInputVariable order="0" name="profileID" />
		<PLOutputVariable name="profile_id" type="string" />
		<PLOutputVariable name="profilename" type="string" />
		<PLOutputVariable name="relationshiptype" type="string" />
		<PLOutputVariable name="daterequested" type="string" />
	</PLSelect>
	<PLSelect name="getProfileRelationships"
		functionName="getProfileRelationships" multipleResults="true">
		<PLInputVariable order="0" name="profileID" />
		<PLOutputVariable name="profile_id" type="string" />
		<PLOutputVariable name="profilename" type="string" />
		<PLOutputVariable name="relationshiptype" type="string" />
	</PLSelect>
	<PLSelect name="endRelationship" functionName="endRelationship"
		multipleResults="false">
		<PLInputVariable order="0" name="requesterProfileID" />
		<PLInputVariable order="1" name="accepterProfileID" />
		<PLInputVariable order="2" name="relationshipType" />
		<PLOutputVariable name="output_Successful" type="boolean" />
	</PLSelect>
	<PLSelect name="getProfileRelationshipTypes"
		functionName="getProfileRelationshipTypes" multipleResults="true">
		<PLInputVariable order="0" name="requesterProfileID" />
		<PLInputVariable order="1" name="accepterProfileID" />
		<PLOutputVariable name="relationshiptype" type="string" />
	</PLSelect>
	<PLSelect name="getProfileName"
		functionName="getProfileName" multipleResults="false">
		<PLInputVariable order="0" name="profileID" />
		<PLOutputVariable name="output_profile_name" type="string" />
	</PLSelect>
	<PLSelect name="getLatestBlog" functionName="getLatestBlog"
		multipleResults="false">
		<PLInputVariable order="0" name="profileID" />
		<PLOutputVariable name="output_blogid" type="string" />
		<PLOutputVariable name="output_dateblogcreated" type="string" />
		<PLOutputVariable name="output_dateedited" type="string" />
		<PLOutputVariable name="output_blogtitle" type="string" />
		<PLOutputVariable name="output_blogcontent" type="string" />
	</PLSelect>
	<PLSelect name="getBlogList" functionName="getBlogList"
		multipleResults="true">
		<PLInputVariable order="0" name="profileID" />
		<PLOutputVariable name="blog_id" type="string" />
		<PLOutputVariable name="dateblogcreated" type="string" />
		<PLOutputVariable name="blogtitle" type="string" />
	</PLSelect>
	<PLSelect name="getBlog" functionName="viewBlog"
		multipleResults="false">
		<PLInputVariable order="0" name="inputBlogID" />
		<PLOutputVariable name="output_blogwriter" type="string" />
		<PLOutputVariable name="output_dateblogcreated" type="string" />
		<PLOutputVariable name="output_dateedited" type="string" />
		<PLOutputVariable name="output_blogtitle" type="string" />
		<PLOutputVariable name="output_blogcontent" type="string" />
	</PLSelect>
	<PLSelect name="createBlog" functionName="createNewBlog"
		multipleResults="false">
		<PLInputVariable order="0" name="profileID" />
		<PLInputVariable order="1" name="blogTitle" />
		<PLInputVariable order="2" name="blogContent" />
		<PLOutputVariable name="output_successful" type="boolean" />
	</PLSelect>
	<PLSelect name="editBlog" functionName="editBlog"
		multipleResults="false">
		<PLInputVariable order="0" name="inputBlogId" />
		<PLInputVariable order="1" name="inputBlogTitle" />
		<PLInputVariable order="2" name="inputBlogContent" />
		<PLOutputVariable name="output_successful" type="boolean" />
	</PLSelect>
	<PLSelect name="deleteBlog" functionName="deleteBlog"
		multipleResults="false">
		<PLInputVariable order="0" name="inputBlogId" />
		<PLOutputVariable name="output_successful" type="boolean" />
	</PLSelect>
	<PLSelect name="createNewImageFile" functionName="createNewImageFile"
		multipleResults="false">
		<PLInputVariable order="0" name="filehash" />
		<PLInputVariable order="1" name="file" />
		<PLInputVariable order="2" name="mimetype" />
		<PLInputVariable order="3" name="filesize" />
		<PLInputVariable order="4" name="profileID" />
		<PLInputVariable order="5" name="filename" />
		<PLInputVariable order="6" name="imagedimensionx" />
		<PLInputVariable order="7" name="imagedimensiony" />
		<PLOutputVariable name="output_successful" type="boolean" />
		<PLOutputVariable name="output_dateuploaded" type="string" />
	</PLSelect>
	<PLSelect name="getProfileImage" functionName="getProfileImageElement"
		multipleResults="false">
		<PLInputVariable order="0" name="profileID" />
		<PLOutputVariable name="output_element_id" type="string" />
		<PLOutputVariable name="output_elementtype_id" type="string" />
		<PLOutputVariable name="output_elementtype" type="string" />
		<PLOutputVariable name="output_elementpackagepath" type="string" />
		<PLOutputVariable name="output_creator_id" type="string" />
		<PLOutputVariable name="output_datecreated" type="string" />
		<PLOutputVariable name="output_imagefilehash" type="string" />
		<PLOutputVariable name="output_mimetype" type="string" />
		<PLOutputVariable name="output_file" type="string" />
		<PLOutputVariable name="output_filesize" type="string" />
		<PLOutputVariable name="output_dateuploaded" type="string" />
		<PLOutputVariable name="output_uploader" type="string" />
		<PLOutputVariable name="output_filename" type="string" />
		<PLOutputVariable name="output_imagedimensionx" type="string" />
		<PLOutputVariable name="output_imagedimensiony" type="string" />
	</PLSelect>
	<PLSelect name="setProfileImage" functionName="setprofileimage"
		multipleResults="false">
		<PLInputVariable order="0" name="userID" />
		<PLInputVariable order="1" name="profileID" />
		<PLInputVariable order="2" name="imagefilehash" />
		<PLInputVariable order="3" name="mimetype" />
		<PLOutputVariable name="output_successful" type="boolean" />
		<PLOutputVariable name="output_element_id" type="string" />
		<PLOutputVariable name="output_elementtype_id" type="string" />
		<PLOutputVariable name="output_elementtype" type="string" />
		<PLOutputVariable name="output_elementpackagepath" type="string" />
	</PLSelect>
	
	<PLSelect name="createBlogComment" functionName="createBlogComment" multipleResults="false">
