=== GunioRobot/eglooframework/trunk/xml3/schemas/Requests.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="com.egloo.www/Requests"
	xmlns="http://www.w3.org/2001/XMLSchema"
	xmlns:tns="com.egloo.www/Requests">



	<complexType name="Request">
		<sequence>
			<element name="Requirement" type="string"
				maxOccurs="unbounded" minOccurs="0">
			</element>
			<element name="BoolArgument" type="tns:BoolArgument"
				maxOccurs="unbounded" minOccurs="0">
			</element>
			<element name="SelectArgument" type="tns:SelectArgument"
				maxOccurs="unbounded" minOccurs="0">
			</element>
			<element name="VariableArgument" type="tns:VariableArgument"
				maxOccurs="unbounded" minOccurs="0">
			</element>
			<element name="Depend" type="tns:Depend"
				maxOccurs="unbounded" minOccurs="0">
			</element>
			<element name="Decorator" type="tns:Decorator"
				maxOccurs="unbounded" minOccurs="0">
			</element>
		</sequence>
		<attribute name="id" type="string" use="required"></attribute>
		<attribute name="processorID" type="string" use="required"></attribute>
	</complexType>

	<complexType name="RequestClass">
		<sequence>
			<element name="Request" type="tns:Request"
				maxOccurs="unbounded" minOccurs="1">
			</element>
		</sequence>
		<attribute name="id" type="string" use="required"></attribute>
	</complexType>



	<complexType name="Depend">
		<sequence>
			<element name="Child" type="tns:Child" maxOccurs="unbounded"
				minOccurs="1">
			</element>

		</sequence>
		<attribute name="id" type="string" use="required"></attribute>
		<attribute name="type" type="string" use="required"></attribute>
	</complexType>


	<complexType name="SelectArgument">
		<sequence maxOccurs="unbounded" minOccurs="0">
			<element name="value" type="tns:value" maxOccurs="unbounded"
				minOccurs="0">
			</element>
		</sequence>
		<attribute name="id" type="string" use="required"></attribute>
		<attribute name="type" type="string" use="required"></attribute>
		<attribute name="required" type="string" use="required"></attribute>
	</complexType>

	<complexType name="VariableArgument">
		<attribute name="id" type="string" use="required"></attribute>
		<attribute name="regex" type="string" use="required"></attribute>
		<attribute name="type" type="string" use="required"></attribute>
		<attribute name="required" type="string" use="required"></attribute>
	</complexType>

	<complexType name="BoolArgument">
		<attribute name="id" type="string" use="required"></attribute>
		<attribute name="type" type="string" use="required"></attribute>
		<attribute name="required" type="string" use="required"></attribute>
	</complexType>



	<complexType name="Child">
		<attribute name="id" type="string" use="required"></attribute>
		<attribute name="type" type="string" use="required"></attribute>
	</complexType>



	<element name="Requests" type="tns:Requests"></element>

	<complexType name="Requests">
		<sequence>
			<element name="RequestClass" type="tns:RequestClass"
				maxOccurs="unbounded" minOccurs="1">
			</element>
		</sequence>
	</complexType>




	<simpleType name="value">
		<restriction base="string"></restriction>
	</simpleType>

	<complexType name="Decorator">
		<attribute name="decoratorID" type="string" use="required"></attribute>
		<attribute name="order" type="int" use="required"></attribute>
	</complexType>
</schema>

=== GunioRobot/eglooframework/Applications/Skeleton/XML/Requests.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
 * Skeleton eGloo Application Request Dispatch File
 *
 * Dispatches HTTP requests to the skeleton eGloo application
 *
 * HTTP requests are mapped via request class and request ID to an
 * appropriate RequestProcessor subclass.  Arguments allowed and
 * decorators applied are specified within the request ID.  The
 * three argument types allowed are variable arguments, boolean
 * arguments and select arguments.  Decorators are applied in a
 * layered fashion according to their order number. 
 * 
 * Copyright 2009 eGloo, LLC
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *        http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *  
 * @author George Cooper
 * @copyright 2009 eGloo, LLC
 * @license http://www.apache.org/licenses/LICENSE-2.0
 * @package XMLHTTPResponse
 * @version 1.0
 -->
<tns:Requests xmlns:tns="com.egloo.www/Requests" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="com.egloo.www/Requests schemas/Requests.xsd">
	<RequestClass id="css"></RequestClass>
	<RequestClass id="externalMainPage">
		<Request id="extMainViewBase" processorID="ExternalMainPageBaseRequestProcessor"></Request>
	</RequestClass>
	<RequestClass id="image">
		<Request id="rawfile" processorID="ImageRawFileRequestProcessor">
			<VariableArgument type="get" id="image_name" regex="~^[a-z0-9/]+?(.gif|.png|.jpg|.jpeg)$~i" required="true" />
			<Decorator order="0" decoratorID="GenericCacheAllDecorator" />
		</Request>
	</RequestClass>
	<RequestClass id="javascript">
<!--
		<Request id="jquery" processorID="JavascriptRequestProcessor">
			<Decorator order="0" decoratorID="GenericCacheAllDecorator" />
		</Request>
-->
	</RequestClass>
</tns:Requests>
