=== GunioRobot/eglooframework/XML/Schemas/eGlooConfiguration.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsi:schema
    xmlns:xsi="http://www.w3.org/2001/XMLSchema"
    xmlns:tns="com.egloo.www/eGlooConfiguration"
    targetNamespace="com.egloo.www/eGlooConfiguration">

    <xsi:element name="Configuration" type="tns:Configuration"></xsi:element>

    <xsi:complexType name="Component">
        <xsi:attribute name="id" type="xsi:string" use="required"></xsi:attribute>
        <xsi:attribute name="displayName" type="xsi:string" use="required"></xsi:attribute>
        <xsi:attribute name="override" type="xsi:string" use="required"></xsi:attribute>
        <xsi:attribute name="type" type="xsi:string" use="required"></xsi:attribute>
        <xsi:attribute name="value" type="xsi:string" use="required"></xsi:attribute>
        <xsi:attribute name="required" type="xsi:string" use="required"></xsi:attribute>
    </xsi:complexType>
    
    <xsi:complexType name="Option">
        <xsi:attribute name="id" type="xsi:string" use="required"></xsi:attribute>
        <xsi:attribute name="displayName" type="xsi:string" use="required"></xsi:attribute>
        <xsi:attribute name="override" type="xsi:string" use="required"></xsi:attribute>
        <xsi:attribute name="type" type="xsi:string" use="required"></xsi:attribute>
        <xsi:attribute name="value" type="xsi:string" use="required"></xsi:attribute>
        <xsi:attribute name="required" type="xsi:string" use="required"></xsi:attribute>
    </xsi:complexType>

    <xsi:complexType name="Configuration">
        <xsi:sequence>
            <xsi:element name="Applications" type="tns:Applications"
                maxOccurs="1" minOccurs="1">
            </xsi:element>
            <xsi:element name="Caching" type="tns:Cubes"
                maxOccurs="1" minOccurs="1">
            </xsi:element>
            <xsi:element name="Cubes" type="tns:Cubes"
                maxOccurs="1" minOccurs="1">
            </xsi:element>
            <xsi:element name="Databases" type="tns:Databases"
                maxOccurs="1" minOccurs="1">
            </xsi:element>
            <xsi:element name="Documents" type="tns:Documents"
                maxOccurs="1" minOccurs="1">
            </xsi:element>
            <xsi:element name="Framework" type="tns:Framework"
                maxOccurs="1" minOccurs="1">
            </xsi:element>
            <xsi:element name="Library" type="tns:Library"
                maxOccurs="1" minOccurs="1">
            </xsi:element>
            <xsi:element name="Network" type="tns:Network"
                maxOccurs="1" minOccurs="1">
            </xsi:element>
            <xsi:element name="Peering" type="tns:Peering"
                maxOccurs="1" minOccurs="1">
            </xsi:element>
            <xsi:element name="System" type="tns:System"
                maxOccurs="1" minOccurs="1">
            </xsi:element>
        </xsi:sequence>
        <!--
        <xsi:attribute name="id" type="xsi:string" use="required"></xsi:attribute>
        <xsi:attribute name="processorID" type="xsi:string" use="required"></xsi:attribute>
        -->
    </xsi:complexType>

    <xsi:complexType name="Applications">
        <!-- Application Configuration -->
        <xsi:sequence>
            <xsi:element name="Component" type="tns:Component"
                maxOccurs="unbounded" minOccurs="0">
            </xsi:element>
            <xsi:element name="Option" type="tns:Option"
                maxOccurs="unbounded" minOccurs="0">
            </xsi:element>
        </xsi:sequence>
    </xsi:complexType>

    <xsi:complexType name="Caching">
        <!-- Caching Configuration -->
        <xsi:sequence>
            <xsi:element name="Component" type="tns:Component"
                maxOccurs="unbounded" minOccurs="0">
            </xsi:element>
            <xsi:element name="Option" type="tns:Option"
                maxOccurs="unbounded" minOccurs="0">
            </xsi:element>
        </xsi:sequence>
    </xsi:complexType>
    
    <xsi:complexType name="Cubes">
        <!-- Cube Configuration -->
        <xsi:sequence>
            <xsi:element name="Component" type="tns:Component"
                maxOccurs="unbounded" minOccurs="0">
            </xsi:element>
            <xsi:element name="Option" type="tns:Option"
                maxOccurs="unbounded" minOccurs="0">
            </xsi:element>
        </xsi:sequence>
    </xsi:complexType>

    <xsi:complexType name="Databases">
        <!-- Database Configuration -->
        <xsi:sequence>
            <xsi:element name="Component" type="tns:Component"
                maxOccurs="unbounded" minOccurs="0">
            </xsi:element>
            <xsi:element name="Option" type="tns:Option"
                maxOccurs="unbounded" minOccurs="0">
            </xsi:element>
        </xsi:sequence>
    </xsi:complexType>
    
    <xsi:complexType name="Documents">
        <!-- eGloo Document Configuration -->
        <xsi:sequence>
            <xsi:element name="Component" type="tns:Component"
                maxOccurs="unbounded" minOccurs="0">
            </xsi:element>
            <xsi:element name="Option" type="tns:Option"
                maxOccurs="unbounded" minOccurs="0">
            </xsi:element>
        </xsi:sequence>
    </xsi:complexType>

    <xsi:complexType name="Framework">
        <!-- eGloo Framework Configuration Options -->
        <xsi:sequence>
            <xsi:element name="Component" type="tns:Component"
                maxOccurs="unbounded" minOccurs="0">
            </xsi:element>
            <xsi:element name="Option" type="tns:Option"
                maxOccurs="unbounded" minOccurs="0">
            </xsi:element>
        </xsi:sequence>
    </xsi:complexType>

    <xsi:complexType name="Library">
        <!-- External Software Support (Smarty, Doctrine, etc) -->
        <xsi:sequence>
            <xsi:element name="Component" type="tns:Component"
                maxOccurs="unbounded" minOccurs="0">
            </xsi:element>
            <xsi:element name="Option" type="tns:Option"
                maxOccurs="unbounded" minOccurs="0">
            </xsi:element>
        </xsi:sequence>
    </xsi:complexType>

    <xsi:complexType name="Network">
        <!-- Networking and eGlooHub Integration -->
        <xsi:sequence>
            <xsi:element name="Component" type="tns:Component"
                maxOccurs="unbounded" minOccurs="0">
            </xsi:element>
            <xsi:element name="Option" type="tns:Option"
                maxOccurs="unbounded" minOccurs="0">
            </xsi:element>
        </xsi:sequence>
    </xsi:complexType>

    <xsi:complexType name="Peering">
        <!-- Load Balancing and Peer-based Redundancy -->
        <xsi:sequence>
            <xsi:element name="Component" type="tns:Component"
                maxOccurs="unbounded" minOccurs="0">
            </xsi:element>
            <xsi:element name="Option" type="tns:Option"
                maxOccurs="unbounded" minOccurs="0">
            </xsi:element>
        </xsi:sequence>
    </xsi:complexType>

    <xsi:complexType name="System">
        <!-- Host Environment and System Support -->
        <xsi:sequence>
            <xsi:element name="Component" type="tns:Component"
                maxOccurs="unbounded" minOccurs="0">
            </xsi:element>
            <xsi:element name="Option" type="tns:Option"
                maxOccurs="unbounded" minOccurs="0">
            </xsi:element>
        </xsi:sequence>
    </xsi:complexType>

</xsi:schema>

=== GunioRobot/eglooframework/Applications/eGloo/Default.gloo/Configuration/Config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--* Custom Generated eGloo Framework Configuration File *-->
<tns:Configuration xmlns:tns="com.egloo.www/eGlooConfiguration" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="com.egloo.www/eGlooConfiguration ../XML/schemas/eGlooConfiguration.xsd">
  <tns:Applications>
	<!-- Extra Include Paths : These are application root relative -->
    <tns:Component id="ExtraClassPath" displayName="Extra Class Path" override="false" type="path" value="../Common/PHP"/>
    <tns:Option id="customVariable2" displayName="customVariable2" override="true" type="customVariable" value="foo1"/>
    <tns:Option id="customVariable3" displayName="customVariable3" override="true" type="customVariable" value="foo2"/>
	<tns:Option id="AppBuild" displayName="Build" override="false" type="path" value="../BUILD"/>
	<tns:Option id="AppMaintenanceVersion" displayName="Maintenance Version" override="false" type="" value="1"/>
	<tns:Option id="AppMajorVersion" displayName="Major Version" override="false" type="" value="3"/>
	<tns:Option id="AppMinorVersion" displayName="Minor Version" override="false" type="" value="0"/>
  </tns:Applications>
</tns:Configuration>

=== GunioRobot/eglooframework/XML/eGlooConfiguration.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
    * Standard eGloo Framework Configuration File
    *
    * Copyright 2009 eGloo, LLC
    * 
    * Licensed under the Apache License, Version 2.0 (the "License");
    * you may not use this file except in compliance with the License.
    * You may obtain a copy of the License at
    * 
    *        http://www.apache.org/licenses/LICENSE-2.0
    * 
    * Unless required by applicable law or agreed to in writing, software
    * distributed under the License is distributed on an "AS IS" BASIS,
    * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    * See the License for the specific language governing permissions and
    * limitations under the License.
    *  
    * @author George Cooper
    * @copyright 2009 eGloo, LLC
    * @license http://www.apache.org/licenses/LICENSE-2.0
    * @package XMLHTTPResponse
    * @version 1.0
-->
<tns:Configuration xmlns:tns="com.egloo.www/eGlooConfiguration" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="com.egloo.www/eGlooConfiguration schemas/eGlooConfiguration.xsd">
    <Applications>
        <Component id="" displayName="" override="" type="" value="" required=""/>
        <Option id="" displayName="" override="" type="" value="" required=""/>
        <Option id="UseDoctrine" displayName="" override="true" type="" value="" required="true"/>
        <Option id="UseSmarty" displayName="" override="true" type="" value="" required="true"/>
    </Applications>
    <Caching>
        <Component id="CachePath" displayName="Cache Path" override="false" type="path" value="" required="true"/>
        <Option id="egCacheEnabled" displayName="eGloo Caching Enabled" override="" type="" value="" required="true"/>
        <Option id="egAPCCacheEnabled" displayName="eGloo APC Caching Enabled" override="" type="" value="" required="true"/>
        <Option id="egFileCacheEnabled" displayName="eGloo File Caching Enabled" override="" type="" value="" required="true"/>
        <Option id="egMemcacheCacheEnabled" displayName="eGloo Memcache Caching Enabled" override="" type="" value="" required="true"/>
    </Caching>
    <Cubes>
        <Component id="CubesPath" displayName="Cubes Path" override="false" type="path" value="" required="true"/>
        <Option id="" displayName="" override="" type="" value="" required=""/>
    </Cubes>
    <Databases>
        <Component id="" displayName="" override="" type="" value="" required=""/>
        <Option id="" displayName="" override="" type="" value="" required=""/>
    </Databases>
    <Documents>
        <Component id="" displayName="" override="" type="" value="" required=""/>
        <Option id="" displayName="" override="" type="" value="" required=""/>
    </Documents>
    <Framework>
        <Component id="FrameworkRootPath" displayName="Framework Root Path" override="false" type="path" value="" required="true"/>
        <Option id="" displayName="" override="" type="" value="" required=""/>
    </Framework>
    <Library>
        <Component id="DoctrinePath" displayName="Doctrine Path" override="false" type="path" value="" required="true"/>
        <Component id="SmartyPath" displayName="Smarty Path" override="false" type="path" value="" required="true"/>
        <Option id="" displayName="" override="" type="" value="" required=""/>
    </Library>
    <Network>
        <Component id="" displayName="" override="" type="" value="" required=""/>
        <Option id="" displayName="" override="" type="" value="" required=""/>
    </Network>
    <Peering>
        <Component id="" displayName="" override="" type="" value="" required=""/>
        <Option id="" displayName="" override="" type="" value="" required=""/>
    </Peering>
    <System>
        <Component id="ApplicationsPath" displayName="Applications Path" override="false" type="path" value="" required="true"/>
        <Component id="CachePath" displayName="Cache Path" override="false" type="path" value="" required="true"/>
        <Component id="CompiledTemplatesPath" displayName="Compiled Templates Path" override="false" type="path" value="" required="true"/>
        <Component id="ConfigurationPath" displayName="Configuration Path" override="false" type="path" value="" required="true"/>
        <Component id="CubesPath" displayName="Cubes Path" override="false" type="path" value="" required="true"/>
        <Component id="DoctrinePath" displayName="Doctrine Path" override="false" type="path" value="" required="true"/>
        <Component id="DocumentationPath" displayName="Documentation Path" override="false" type="path" value="" required="true"/>
        <Component id="DocumentRoot" displayName="Document Root" override="false" type="path" value="" required="true"/>
        <Component id="FrameworkRootPath" displayName="Framework Root Path" override="false" type="path" value="" required="true"/>
        <Component id="LoggingPath" displayName="Logging Path" override="false" type="path" value="" required="true"/>
        <Component id="SmartyPath" displayName="Smarty Path" override="false" type="path" value="" required="true"/>

        <Option id="egApplication" displayName="Default System Application" override="true" type="enum" value="DEVELOPMENT" required="true"/>
        <Option id="egEnvironment" displayName="eGloo Environment" override="true" type="enum" value="DEVELOPMENT" required="true"/>
        <Option id="egInterfaceBundle" displayName="Default System Interface Bundle" override="true" type="enum" value="DEVELOPMENT" required="true"/>
        <Option id="UseSmarty" displayName="" override="true" type="" value="" required="true"/>
        
        <Option id="UseDoctrine" displayName="" override="true" type="" value="" required="true"/>
        <Option id="UseSmarty" displayName="" override="true" type="" value="" required="true"/>
            
            # Application / Bundle Selection
            SetEnv EG_APP eGloo/Default.gloo
            SetEnv EG_UI  OverlayInterface
            # SetEnv EG_UI  Default
            # SetEnv EG_APP Demos/PetFood
            # SetEnv EG_UI Default
            # SetEnv EG_APP Demos/BookResale
            # SetEnv EG_UI Default
            # SetEnv EG_APP Demos/DogOwners
            # SetEnv EG_UI Default
            # SetEnv EG_APP Demos/ImageHosting
            # SetEnv EG_UI Default
            # SetEnv EG_APP Incentient/Client
            # SetEnv EG_UI Default
            
            # Caching
            
            # Database Engine
            SetEnv EG_DB_ENGINE POSTGRESQL
            # SetEnv EG_DB_ENGINE MYSQL
            
            # Errors
            SetEnv EG_DISPLAY_ERRORS ON
            SetEnv EG_DISPLAY_TRACES ON
            
            # Logging
            # SetEnv EG_LOG_LEVEL PRODUCTION
            # SetEnv EG_LOG_LEVEL STAGING
            SetEnv EG_LOG_LEVEL DEVELOPMENT
            SetEnv EG_LOG_FORMAT LOG
            
            SetEnv EG_REWRITE_BASE /egloo
            
        -->
        
    </System>
</tns:Configuration>

=== GunioRobot/eglooframework/Applications/eGloo/Default.gloo/XML/eGlooConfiguration.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
    * Standard eGloo Framework Configuration File
    *
    * Copyright 2010 eGloo, LLC
    * 
    * Licensed under the Apache License, Version 2.0 (the "License");
    * you may not use this file except in compliance with the License.
    * You may obtain a copy of the License at
    * 
    *        http://www.apache.org/licenses/LICENSE-2.0
    * 
    * Unless required by applicable law or agreed to in writing, software
    * distributed under the License is distributed on an "AS IS" BASIS,
    * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    * See the License for the specific language governing permissions and
    * limitations under the License.
    *  
    * @author George Cooper
    * @copyright 2011 eGloo, LLC
    * @license http://www.apache.org/licenses/LICENSE-2.0
    * @package XMLHTTPResponse
    * @version 1.0
-->
<tns:Configuration xmlns:tns="com.egloo.www/eGlooConfiguration" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="com.egloo.www/eGlooConfiguration schemas/eGlooConfiguration.xsd">
    <Applications>
        <Component id="" displayName="" override="" type="" value="" required=""/>
        <Option id="" displayName="" override="" type="" value="" required=""/>
        <Option id="UseDoctrine" displayName="" override="true" type="" value="" required="true"/>
        <Option id="UseSmarty" displayName="" override="true" type="" value="" required="true"/>
    </Applications>
    <Caching>
        <Component id="CachePath" displayName="Cache Path" override="false" type="path" value="" required="true"/>
        <Option id="egCacheEnabled" displayName="eGloo Caching Enabled" override="" type="" value="" required="true"/>
        <Option id="egAPCCacheEnabled" displayName="eGloo APC Caching Enabled" override="" type="" value="" required="true"/>
        <Option id="egFileCacheEnabled" displayName="eGloo File Caching Enabled" override="" type="" value="" required="true"/>
        <Option id="egMemcacheCacheEnabled" displayName="eGloo Memcache Caching Enabled" override="" type="" value="" required="true"/>
    </Caching>
    <Cubes>
        <Component id="CubesPath" displayName="Cubes Path" override="false" type="path" value="" required="true"/>
        <Option id="" displayName="" override="" type="" value="" required=""/>
    </Cubes>
    <Databases>
        <Component id="" displayName="" override="" type="" value="" required=""/>
        <Option id="" displayName="" override="" type="" value="" required=""/>
    </Databases>
    <Documents>
        <Component id="" displayName="" override="" type="" value="" required=""/>
        <Option id="" displayName="" override="" type="" value="" required=""/>
    </Documents>
    <Framework>
        <Component id="FrameworkRootPath" displayName="Framework Root Path" override="false" type="path" value="" required="true"/>
        <Option id="" displayName="" override="" type="" value="" required=""/>
    </Framework>
    <Library>
        <Component id="DoctrinePath" displayName="Doctrine Path" override="false" type="path" value="" required="true"/>
        <Component id="SmartyPath" displayName="Smarty Path" override="false" type="path" value="" required="true"/>
        <Option id="" displayName="" override="" type="" value="" required=""/>
    </Library>
    <Network>
        <Component id="" displayName="" override="" type="" value="" required=""/>
        <Option id="" displayName="" override="" type="" value="" required=""/>
    </Network>
    <Peering>
        <Component id="" displayName="" override="" type="" value="" required=""/>
        <Option id="" displayName="" override="" type="" value="" required=""/>
    </Peering>
    <System>
        <!-- Components -->
        <Component id="ApplicationsPath" displayName="Applications Path" override="false" type="path" value="" required="true"/>
        <Component id="CachePath" displayName="Cache Path" override="false" type="path" value="" required="true"/>
        <Component id="ConfigurationPath" displayName="Configuration Path" override="false" type="path" value="" required="true"/>
        <Component id="CubesPath" displayName="Cubes Path" override="false" type="path" value="" required="true"/>
        <Component id="DoctrinePath" displayName="Doctrine Path" override="false" type="path" value="" required="true"/>
        <Component id="DocumentationPath" displayName="Documentation Path" override="false" type="path" value="" required="true"/>
        <Component id="DocumentRoot" displayName="Document Root" override="false" type="path" value="" required="true"/>
        <Component id="FrameworkRootPath" displayName="Framework Root Path" override="false" type="path" value="" required="true"/>
        <Component id="LoggingPath" displayName="Logging Path" override="false" type="path" value="" required="true"/>
        <Component id="SmartyPath" displayName="Smarty Path" override="false" type="path" value="" required="true"/>

        <!-- Application / Bundle Selection -->
        <Option id="egApplication" displayName="Default System Application" override="true" type="enum" value="eGloo/Default.gloo" required="true"/>
        <Option id="egInterfaceBundle" displayName="Default System Interface Bundle" override="true" type="enum" value="OverlayInterface" required="true"/>

        <!--
        <Option id="egApplication" displayName="Default System Application" override="true" type="enum" value="Demos/PetFood.gloo" required="true"/>
        <Option id="egInterfaceBundle" displayName="Default System Interface Bundle" override="true" type="enum" value="Default" required="true"/>
        <Option id="egApplication" displayName="Default System Application" override="true" type="enum" value="Demos/BookResale.gloo" required="true"/>
        <Option id="egInterfaceBundle" displayName="Default System Interface Bundle" override="true" type="enum" value="Default" required="true"/>
        <Option id="egApplication" displayName="Default System Application" override="true" type="enum" value="Demos/DogOwners.gloo" required="true"/>
        <Option id="egInterfaceBundle" displayName="Default System Interface Bundle" override="true" type="enum" value="Default" required="true"/>
        <Option id="egApplication" displayName="Default System Application" override="true" type="enum" value="Demos/ImageHosting.gloo" required="true"/>
        <Option id="egInterfaceBundle" displayName="Default System Interface Bundle" override="true" type="enum" value="Default" required="true"/>
        -->
        
        <!-- Database Engine -->
        <Option id="egDatabaseEngine" displayName="eGloo Database Engine" override="true" type="enum" value="POSTGRESQL" required="true"/>
        <!-- <Option id="egDatabaseEngine" displayName="eGloo Database Engine" override="true" type="enum" value="MYSQL" required="true"/> -->

        <!-- Deployment -->
        <Option id="egEnvironment" displayName="eGloo Environment" override="true" type="enum" value="DEVELOPMENT" required="true"/>
        
        <!-- Errors -->
        <Option id="egDisplayErrors" displayName="Display Errors" override="true" type="bool" value="TRUE" required="true"/>
        <Option id="egDisplayTraces" displayName="Display Error Traces" override="true" type="bool" value="TRUE" required="true"/>
        
        <!-- Logging -->
        <Option id="egLogLevel" displayName="eGloo Logging Level" override="true" type="enum" value="PRODUCTION" required="true"/>
        
        <!--
        <Option id="egLogLevel" displayName="eGloo Logging Level" override="true" type="enum" value="STAGING" required=""/>
        <Option id="egLogLevel" displayName="eGloo Logging Level" override="true" type="enum" value="DEVELOPMENT" required=""/>
        -->

        <Option id="egLogFormat" displayName="eGloo Log File Format" override="true" type="enum" value="LOG" required="true"/>

        <!-- Rewrite Options /  -->
        <Option id="egRewriteBase" displayName="eGloo Rewrite Base" override="true" type="string" value="/egloo" required="true"/>

        <Option id="UseDoctrine" displayName="" override="true" type="" value="" required="true"/>
        <Option id="UseSmarty" displayName="" override="true" type="" value="" required="true"/>        
    </System>
</tns:Configuration>
